apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-client
spec:
  type: {{ .Values.client.service.type }}
  selector:
    app: whiteboard-client-selector
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.targetPort }}
      protocol: TCP

