apiVersion: apps/v1
kind: Deployment
metadata:
  name: whiteboard-client
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app: whiteboard-client-selector
  template:
    metadata:
      annotations:
        deploy-timestamp: "{{ now }}"
      labels:
        app: whiteboard-client-selector
    spec:
      containers:
        - name: client
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "50Mi"
          ports:
            - containerPort: {{ .Values.client.service.targetPort }}
          env:
            {{- range .Values.client.env }}
              - name: {{ .name }}
                value: {{ tpl .value $ | quote }}
            {{- end }}
