apiVersion: apps/v1
kind: Deployment
metadata:
  name: whiteboard-genai
spec:
  replicas: {{ .Values.genai.replicaCount }}
  selector:
    matchLabels:
      app: whiteboard-genai-selector
  template:
    metadata:
      labels:
        app: whiteboard-genai-selector
    spec:
      containers:
        - name: genai
          image: "{{ .Values.genai.image.repository }}:{{ .Values.genai.image.tag }}"
          imagePullPolicy: {{ .Values.genai.image.pullPolicy }}
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "50Mi"
          ports:
            - containerPort: {{ .Values.genai.service.targetPort }}
          env:
            {{- range .Values.genai.env }}
              - name: {{ .name }}
                value: {{ tpl .value $ | quote }}
            {{- end }}
