apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources-configmap
data:
  prometheus.yml: |-
{{- $config := .Files.Get "files/grafana/provisioning/datasources/prometheus.yml" }}
{{ tpl $config . | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-configmap
data:
  dashboards.yml: |
{{ .Files.Get "files/grafana/provisioning/dashboards/dashboards.yml" | indent 4 }}
  server-dashboard.json: |
{{ .Files.Get "files/grafana/provisioning/dashboards/server-dashboard.json" | indent 4 }}