{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "whiteboard-ingress"
  namespace: {{ .Values.namespace  }}
  {{- $annotations := .Values.ingress.annotations | default dict }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        {{- range .Values.ingress.tls.hosts }}
        - {{ tpl . $ | quote }}
        {{- end }}
      secretName: {{ .Values.ingress.tls.secretName }}
  ingressClassName: nginx
  rules:
      {{- range .Values.ingress.rules }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ tpl .service.name $ | quote }}
                port:
                  number: {{ .service.port.number }}
          {{- end}}
      {{- end }}
{{- end }}