apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
spec:
  selector:
    app: whiteboard-server-selector
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
  type: {{ .Values.server.service.type }}