apiVersion: apps/v1
kind: Deployment
metadata:
  name: whiteboard-server
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app: whiteboard-server-selector
  template:
    metadata:
      annotations:
        deploy-timestamp: "{{ now }}"
      labels:
        app: whiteboard-server-selector
    spec:
      containers:
        - name: server
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - containerPort: {{ .Values.server.service.targetPort }}
          env:
            {{- range .Values.server.env }}
            - name: {{ .name }}
              value: {{ tpl .value $ | quote }}
            {{- end }}
