name: team-server-down

services:
  keycloak:
    restart: always
    build:
      context: ./docker/keycloak
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command:
      - start-dev
      - --import-realm
      - -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
      - --transaction-xa-enabled=false
    depends_on:
      db:
        condition: service_healthy
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_HEALTH_ENABLED: true
    volumes:
      - ./docker/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    networks:
      - server

  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/"]
      interval: 10s
      timeout: 3s
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-main}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      ALLOWED_ORIGIN: ${ALLOWED_ORIGIN:-http://localhost:3000}
      IDP_INTERNAL_URI: ${IDP_INTERNAL_URI:-http://keycloak:8080/realms/development}
      IDP_EXTERNAL_URI: ${IDP_EXTERNAL_URI:-http://localhost:8080/realms/development}
      SERVER_URL: ${SERVER_URL:-http://localhost:9091}
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,metrics,prometheus"
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
      MANAGEMENT_ENDPOINT_METRICS_ENABLED: "true"
      MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
      MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
      MANAGEMENT_ENDPOINTS_WEB_BASE_PATH: "/api/actuator"
      SPRING_SECURITY_IGNORED_PATHS: "/api/actuator/**"
      SERVER_ADDRESS: "0.0.0.0" 
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9091:9091"
    volumes:
      - ./server:/app
    networks:
      - server

  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile.local
    entrypoint: npm run dev
    volumes:
      - ./client:/app
      - node-modules-client:/app/node_modules
    healthcheck:
      test: "curl -f http://localhost:3000 || exit 1"
      interval: 5s
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:9091}
      NEXT_PUBLIC_GENAI_URL: ${NEXT_PUBLIC_GENAI_URL:-http://localhost:8000}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000/api/auth/}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-feZJWB3mcQ93VBmqHKQI5er5NEIxcDPb3wtT/KaLB9s=}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID:-webclient}
      KEYCLOAK_ISSUER: ${KEYCLOAK_ISSUER:-http://keycloak:8080/realms/development}
      KEYCLOAK_END_SESSION_ENDPOINT: ${KEYCLOAK_END_SESSION_ENDPOINT:-http://keycloak:8080/realms/development/protocol/openid-connect/logout}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET:-SXiMvr1GG10bk2J63ODZC9SOaoAZ4dbe}
    ports:
      - "3000:3000"
    networks:
      - server

  db:
    restart: always
    build:
      context: ./docker/postgresql
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U root -d main'" ]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - server

  genai:
    restart: always
    build:
      context: ./genai
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_HOST: ${DB_HOST:-weaviate}
      DB_PORT: ${DB_PORT:-9092}
      DB_GRPC_PORT: ${DB_GRPC_PORT:-50051}
    volumes:
      - ./genai:/app
    networks:
      - server
      - rag


  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - "9100:9100"
    networks:
      - server
      - rag

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - server
      - rag

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_FEATURE_TOGGLES_ENABLE=logsInExplore
      - GF_LOG_CONSOLECOLORS=true
   # entrypoint: ["sh", "-c", "/etc/grafana/provisioning/init_grafana.sh"]
    depends_on:
      - prometheus
      - loki
    restart: unless-stopped
    networks:
      - server
      - rag

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail/promtail.yml:/etc/promtail/promtail.yml
    command: -config.file=/etc/promtail/promtail.yml
    depends_on:
      - loki
    restart: unless-stopped
    networks:
      - server
      - rag

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yaml:/loki/loki-config.yaml:ro
      - loki-storage:/loki/data   
    command: -config.file=/loki/loki-config.yaml
    restart: unless-stopped
    networks:
      - server
      - rag
  
  alertmanager:
    image: prom/alertmanager:v0.26.0
    container_name: alertmanager
    volumes:
      - ./alertManager:/etc/alertmanager:ro
      - alertmanager_data:/alertmanager
      
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
      - '--log.level=debug'
    ports:
      - "9093:9093"
    networks:
      - server
      - rag
    restart: unless-stopped

networks:
  server:
  rag:

volumes:
  db-data:
  node-modules-client:
  weaviate-data:
  prometheus_data:
  grafana-storage:
  loki-storage:
  alertmanager_data:

