CREATE TABLE whiteboard
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title           VARCHAR(255),
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    last_updated_at TIMESTAMP WITHOUT TIME ZONE,
    user_id         BIGINT,
    CONSTRAINT pk_whiteboard PRIMARY KEY (id)
);