CREATE TABLE whiteboard
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title            VARCHAR(255),
    creation_time    TIMESTAMP WITHOUT TIME ZONE,
    last_edited_time TIMESTAMP WITHOUT TIME ZONE,
    user_id          BIGINT,
    CONSTRAINT pk_whiteboard PRIMARY KEY (id)
);