CREATE TABLE viewports
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    x             DOUBLE PRECISION                        NOT NULL,
    y             DOUBLE PRECISION                        NOT NULL,
    zoom          DOUBLE PRECISION                        NOT NULL,
    whiteboard_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_viewport PRIMARY KEY (id)
);
