CREATE TABLE user_whiteboard_access
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    whiteboard_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_user_whiteboard_access PRIMARY KEY (id)
);

ALTER TABLE user_whiteboard_access
    ADD CONSTRAINT uc_6e6857928b3cd35a013da0ed2 UNIQUE (user_id, whiteboard_id);

ALTER TABLE user_whiteboard_access
    ADD CONSTRAINT FK_USER_WHITEBOARD_ACCESS_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE user_whiteboard_access
    ADD CONSTRAINT FK_USER_WHITEBOARD_ACCESS_ON_WHITEBOARD FOREIGN KEY (whiteboard_id) REFERENCES whiteboard (id);