server:
  port: 9091

springdoc:
  swagger-ui:
    oauth2-redirect-url: ${SERVER_URL}/swagger-ui/oauth2-redirect.html

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${IDP_INTERNAL_URI}
          jwk-set-uri: ${IDP_INTERNAL_URI}/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    validate-on-migrate: true


management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]
  endpoint:
    prometheus:
      enabled: true
  metrics:
    web:
      server:
        auto-time-requests: true
      request:
        ignore-patterns: "/api/actuator/.*"
        autotime:
          enabled: true

