apiVersion: 1

groups:
  - name: System Usage
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance)(rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100 > 80
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is {{ $value }}% for last 10 minutes (threshold: 80%)"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is {{ $value }}% for last 15 minutes (threshold: 85%)"


  - name: Service Availability
    rules:
      - alert: ServiceDown
        expr: up{job=~"genai|server|client"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} on instance {{ $labels.instance }} has been down for more than 1 minute"

      - alert: ServiceEndpointFailure
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate for {{ $labels.job }}"
          description: "Service {{ $labels.job }} is experiencing errors ({{ $value }} 5xx errors in 5m)"

      - alert: ServiceHighLatency
        expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m]) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High latency for {{ $labels.job }}"
          description: "Service {{ $labels.job }} has high latency ({{ $value }}s) for the last 5 minutes"

