{
 "title": "Server System Metrics Dashboard",
 "description": "Dashboard showing system metrics including request count, latency, and error rate.",
 "tags": [
  "monitoring",
  "alerts"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[5m])) by (method, uri)",
     "legendFormat": "{{method}} {{status}} {{uri}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "    sum(rate(http_server_requests_seconds_sum[5m])) by (method, uri) /\nsum(rate(http_server_requests_seconds_count[5m])) by (method, uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{outcome=\"CLIENT_ERROR\"}[5m])) by (method, uri, status)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[5m])) by (method, uri, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/var/lib/docker/containers/439f2edcd03865b27463c28064f986e4a0d11d8cb3f92ebc3455e5b9175b9412/439f2edcd03865b27463c28064f986e4a0d11d8cb3f92ebc3455e5b9175b9412-json.log\"} |= ``"
    }
   ]
  }
 ]
}