vpc_cidr_block = "10.0.0.0/16"
subnet_1_cidr_block = "10.0.0.0/24"
avail_zone = "us-east-1a"
env_prefix = "dev"
instance_type = "t2.micro"
ssh_key = "/Users/leon.liang/.ssh/teamserverdown.pub"
ssh_private_key = "/Users/leon.liang/.ssh/teamserverdown"