apiVersion: v2
name: whiteboard-observability
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: grafana
    version: 9.2.10
    repository: "https://grafana.github.io/helm-charts"
  - name: prometheus
    version: 27.28.0
    repository: "https://prometheus-community.github.io/helm-charts"
