// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/AET-DevOps25/team-server-down/pkg/api"
	"github.com/AET-DevOps25/team-server-down/pkg/api/handler"
	"github.com/AET-DevOps25/team-server-down/pkg/api/metrics"
	"github.com/AET-DevOps25/team-server-down/pkg/config"
	"github.com/AET-DevOps25/team-server-down/pkg/mq"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*http.Server, error) {
	rootHandler := handler.NewRootHandler()
	redisMQ := mq.NewRedisMQ(cfg)
	registry := metrics.ProvideRegistry()
	metricsMetrics := metrics.ProvideMetrics(registry)
	whiteboardHandler := handler.NewWhiteboardHandler(redisMQ, metricsMetrics)
	server := http.NewServer(rootHandler, whiteboardHandler, registry)
	return server, nil
}
