{
 "title": "Realtime System Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Websocket Connections Active",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "websocket_connections_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connection Duration Summary",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "rate(websocket_connection_duration_sum[5m]) / rate(websocket_connection_duration_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages Sent/Received Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(websocket_sent_messages[1m])",
     "legendFormat": "Messages Sent"
    },
    {
     "expr": "rate(websocket_received_messages[1m])",
     "legendFormat": "Messages Received"
    }
   ]
  },
  {
   "title": "Websocket Connection Duration",
   "type": "bargauge",
   "description": "Distribution of WebSocket connection durations across different time buckets. Each bar represents a cumulative count of connections that lasted less than or equal to the specified duration (in seconds). For example, '60s' shows connections lasting up to 60 seconds, '120s' shows connections up to 120 seconds, and so on up to '+Inf' (unlimited duration).",
   "gridPos": { "h": 17, "w": 14, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "websocket_connection_duration_bucket{le=~\".+\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Websocket Error Rates",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(websocket_read_errors[1m])",
     "legendFormat": "websocket_read_errors"
    },
    {
     "expr": "rate(websocket_write_errors[1m])",
     "legendFormat": "websocket_write_errors"
    },
    {
     "expr": "rate(websocket_upgrade_errors[1m])",
     "legendFormat": "websocket_upgrade_errors"
    }
   ]
  }
 ]
}