namespace: "tsd-prod"
environment: production

client:
  image:
    repository: ghcr.io/aet-devops25/team-server-down/client
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
  replicaCount: 1
  env:
    - name: KEYCLOAK_CLIENT_SECRET
      value: SXiMvr1GG10bk2J63ODZC9SOaoAZ4dbe
    - name: NEXTAUTH_URL
      value: https://whiteboard.student.k8s.aet.cit.tum.de/api/auth/
    - name: NEXTAUTH_SECRET
      value: feZJWB3mcQ93VBmqHKQI5er5NEIxcDPb3wtT/KaLB9s=
    - name: KEYCLOAK_CLIENT_ID
      value: webclient
    - name: KEYCLOAK_ISSUER
      value: https://auth.whiteboard.student.k8s.aet.cit.tum.de/realms/production
    - name: KEYCLOAK_END_SESSION_ENDPOINT
      value: https://auth.whiteboard.student.k8s.aet.cit.tum.de/realms/production/protocol/openid-connect/logout

server:
  image:
    repository: ghcr.io/aet-devops25/team-server-down/server
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 9091
    targetPort: 9091
  env:
    - name: DB_HOST
      value: '{{ printf "%s-postgresql" .Release.Name }}'
    - name: DB_PORT
      value: "5432"
    - name: DB_NAME
      value: postgres
    - name: DB_USER
      value: postgres
    - name: DB_PASSWORD
      value: postgres
    - name: ALLOWED_ORIGIN
      value: "https://whiteboard.student.k8s.aet.cit.tum.de"
    - name: IDP_INTERNAL_URI
      value: "https://auth.whiteboard.student.k8s.aet.cit.tum.de/realms/production"
    - name: IDP_EXTERNAL_URL
      value: "https://auth.whiteboard.student.k8s.aet.cit.tum.de/realms/production"
  replicaCount: 1

postgresql:
  primary:
    extraEnvVars:
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: password
      - name: POSTGRES_MULTIPLE_DATABASES
        value: "main,keycloak"
    extraVolumes:
      - name: db-init
        configMap:
          name: postgresql-configmap
    extraVolumeMounts:
      - name: db-init
        mountPath: /docker-entrypoint-initdb.d

keycloak:
  ingress:
    enabled: true
    hostname: auth.whiteboard.student.k8s.aet.cit.tum.de
  auth:
    adminUser: admin
    adminPassword: password
  postgresql:
    enabled: false
  externalDatabase:
    host: '{{ printf "%s-postgresql" .Release.Name }}'
    user: postgres
    password: password
    database: keycloak
    port: 5432
  extraEnvVars:
    - name: KEYCLOAK_EXTRA_ARGS
      value: "--import-realm"
    - name: KC_PROXY
      value: edge
    - name: KC_PROXY_HEADERS
      value: xforwarded
  extraVolumes:
    - name: realm-export
      configMap:
        name: keycloak-configmap
  extraVolumeMounts:
    - name: realm-export
      mountPath: /opt/bitnami/keycloak/data/import

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
  tls:
    hosts:
      - "whiteboard.student.k8s.aet.cit.tum.de"
      - "api.whiteboard.student.k8s.aet.cit.tum.de"
      - "auth.whiteboard.student.k8s.aet.cit.tum.de"
    secretName: "whiteboard-devops25-tls"
  rules:
    - host: "whiteboard.student.k8s.aet.cit.tum.de"
      paths:
        - path: /
          pathType: Prefix
          service:
            name: client-service
            port:
              number: 3000
    - host: "api.whiteboard.student.k8s.aet.cit.tum.de"
      paths:
        - path: /
          pathType: Prefix
          service:
            name: server-service
            port:
              number: 8080
    - host: "auth.whiteboard.student.k8s.aet.cit.tum.de"
      paths:
        - path: /
          pathType: Prefix
          service:
            name: '{{ printf "%s-keycloak" .Release.Name }}'
            port:
              number: 80