namespace: "tsd-staging"
environment: staging

client:
  image:
    repository: ghcr.io/aet-devops25/team-server-down/client
    tag: develop
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000

  replicaCount: 1

  env:
    - name: KEYCLOAK_CLIENT_SECRET
      value: SXiMvr1GG10bk2J63ODZC9SOaoAZ4dbe
    - name: NEXTAUTH_URL
      value: https://staging.whiteboard.student.k8s.aet.cit.tum.de/api/auth/
    - name: NEXTAUTH_SECRET
      value: feZJWB3mcQ93VBmqHKQI5er5NEIxcDPb3wtT/KaLB9s=
    - name: KEYCLOAK_CLIENT_ID
      value: webclient
    - name: KEYCLOAK_ISSUER
      value: https://staging.auth.whiteboard.student.k8s.aet.cit.tum.de/realms/staging
    - name: KEYCLOAK_END_SESSION_ENDPOINT
      value: https://staging.auth.whiteboard.student.k8s.aet.cit.tum.de/realms/staging/protocol/openid-connect/logout

server:
  image:
    repository: ghcr.io/aet-devops25/team-server-down/server
    tag: develop
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 9091
    targetPort: 9091

  env:
    - name: DB_HOST
      value: '{{ printf "%s-postgresql" .Release.Name }}'
    - name: DB_PORT
      value: "5432"
    - name: DB_NAME
      value: main
    - name: DB_USER
      value: postgres
    - name: DB_PASSWORD
      value: password
    - name: ALLOWED_ORIGIN
      value: "https://staging.whiteboard.student.k8s.aet.cit.tum.de"
    - name: IDP_URI
      value: '{{ printf "%s-keycloak" .Release.Name }}'

  replicaCount: 1


ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
  tls:
    hosts:
      - "staging.whiteboard.student.k8s.aet.cit.tum.de"
      - "staging.api.whiteboard.student.k8s.aet.cit.tum.de"
      - "staging.auth.whiteboard.student.k8s.aet.cit.tum.de"
    secretName: "staging-whiteboard-devops25-tls"
  rules:
    - host: "staging.whiteboard.student.k8s.aet.cit.tum.de"
      paths:
        - path: /
          pathType: Prefix
          service:
              name: client-service
              port:
                number: 3000
    - host: "staging.api.whiteboard.student.k8s.aet.cit.tum.de"
      paths:
        - path: /
          pathType: Prefix
          service:
            name: server-service
            port:
              number: 9091
    - host: "staging.auth.whiteboard.student.k8s.aet.cit.tum.de"
      paths:
        - path: /
          pathType: Prefix
          service:
            name: '{{ printf "%s-keycloak" .Release.Name }}'
            port:
              number: 80

postgresql:
  auth:
    username: postgres
    password: password
  primary:
    extraEnvVars:
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: password
      - name: POSTGRES_MULTIPLE_DATABASES
        value: "main,keycloak"
    extraVolumes:
      - name: db-init
        configMap:
          name: postgresql-configmap
    extraVolumeMounts:
      - name: db-init
        mountPath: /docker-entrypoint-initdb.d

keycloak:
  ingress:
    enabled: true
    hostname:
  auth:
    adminUser: admin
    adminPassword: password
  postgresql:
    enabled: false
  externalDatabase:
    host:
    user: postgres
    password: password
    database: keycloak
    port: 5432
  env:
    - name: KC_DB_URL
      value: '{{ printf "jdbc:postgresql://%s-postgresql:5432/keycloak" .Release.Name }}'
    - name: KC_DB_USERNAME
      value: postgres
    - name: KC_DB_PASSWORD
      value: password
    - name: KEYCLOAK_ADMIN
      value: admin
    - name: KEYCLOAK_ADMIN_PASSWORD
      value: password
    - name: KC_PROXY
      value: passthrough
    - name: KC_HTTP_ENABLED
      value: "true"
    - name: KC_HOSTNAME
      value: staging.auth.whiteboard.student.k8s.aet.cit.tum.de
    - name: KC_HOSTNAME_STRICT
      value: "false"
    - name: KC_HOSTNAME_STRICT_HTTPS
      value: "false"
    - name: KC_PROXY_HEADERS
      value: xforwarded
  volumes:
    - name: realm-export
      configMap:
        name: keycloak-configmap
  volumeMounts:
    - name: realm-export
      mountPath: /opt/bitnami/keycloak/data/import