groups:
  - name: service-availability
    rules:
      - alert: Service Down
        expr: up{job=~"server_job|genai_job"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} on {{ $labels.instance }} has been down for more than 1 minute"