global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

rule_files:
  - "/etc/prometheus/alert.rules.yml"

scrape_configs:
  - job_name: 'server_job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
        - 'server:9091'

  - job_name: 'genai_job'
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'genai:8000'

  - job_name: 'realtime_job'
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'realtime:9090'