name: Cleanup PR Deployment

on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Set variables
        run: |
          BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF##*/}}"
          BRANCH_SAFE=${BRANCH//\//-}
          echo "NAMESPACE=tsd-$BRANCH_SAFE" >> $GITHUB_ENV

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          echo "KUBECONFIG=$(pwd)/kubeconfig" >> $GITHUB_ENV

      - name: Delete Namespace
        run: |
          kubectl --kubeconfig="${KUBECONFIG}" delete namespace ${{ env.NAMESPACE }} --ignore-not-found