name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Build and Push Docker images"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set variables
        run: |
          BRANCH=${GITHUB_REF##*/}
          if [[ "$BRANCH" == "main" ]]; then
            echo "NAMESPACE=tsd-prod" >> $GITHUB_ENV
            echo "IMAGE_TAG=lastest" >> $GITHUB_ENV
            echo "VALUES_FILE=./infrastructure/whiteboard-app/production.values.yaml" >> $GITHUB_ENV
            echo "CLIENT_URL=https://whiteboard.student.k8s.aet.cit.tum.de" >> $GITHUB_ENV
            echo "SERVER_URL=https://api.whiteboard.student.k8s.aet.cit.tum.de" >> $GITHUB_ENV
            echo "AUTH_URL=https://auth.whiteboard.student.k8s.aet.cit.tum.de" >> $GITHUB_ENV
          elif [[ "$BRANCH" == "develop" ]]; then
            echo "NAMESPACE=tsd-staging" >> $GITHUB_ENV
            echo "IMAGE_TAG=develop" >> $GITHUB_ENV
            echo "VALUES_FILE=./infrastructure/whiteboard-app/staging.values.yaml" >> $GITHUB_ENV
            echo "CLIENT_URL=https://staging.whiteboard.student.k8s.aet.cit.tum.de" >> $GITHUB_ENV
            echo "SERVER_URL=https://staging.api.whiteboard.student.k8s.aet.cit.tum.de" >> $GITHUB_ENV
            echo "AUTH_URL=https://staging.auth.whiteboard.student.k8s.aet.cit.tum.de" >> $GITHUB_ENV
          else
            BRANCH_SAFE=${BRANCH//\//-}
            echo "NAMESPACE=tsd-$BRANCH_SAFE" >> $GITHUB_ENV
            echo "IMAGE_TAG=$BRANCH_SAFE" >> $GITHUB_ENV 
            echo "VALUES_FILE=./infrastructure/whiteboard-app/pullrequest.values.yaml" >> $GITHUB_ENV
            echo "CLIENT_URL=https://$BRANCH_SAFE.whiteboard.student.k8s.aet.cit.tum.de" >> $GITHUB_ENV
            echo "SERVER_URL=https://$BRANCH_SAFE.api.whiteboard.student.k8s.aet.cit.tum.de" >> $GITHUB_ENV
            echo "AUTH_URL=https://$BRANCH_SAFE.auth.whiteboard.student.k8s.aet.cit.tum.de" >> $GITHUB_ENV
          fi

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          echo "KUBECONFIG=$(pwd)/kubeconfig" >> $GITHUB_ENV

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Deploy App with Helm
        run: |
          helm upgrade whiteboard ./infrastructure/whiteboard-app/ \
            -f ${{ env.VALUES_FILE }} \
            -n ${{ env.NAMESPACE }} \
            --create-namespace \
            --install \
            --atomic \
            --kubeconfig ${{ env.KUBECONFIG }} \
            --set namespace=${{ env.NAMESPACE }} \
            --set server.image.tag=${{ env.IMAGE_TAG }} \
            --set client.image.tag=${{ env.IMAGE_TAG }} \
            --set client.url=${{ env.CLIENT_URL }} \
            --set server.url=${{ env.SERVER_URL }} \
            --set auth.url=${{ env.AUTH_URL }}