name: GenAI tests

on:
  pull_request:
    paths:
      - 'genai/**'
  workflow_dispatch:

jobs:
  genai-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "./genai/.python-version"

      - name: Install dependencies
        run: |
          uv pip install -r ./genai/requirements.txt --system

      - name: GenAI tests
        env:
         OPEN_WEB_UI_API_KEY: ${{ secrets.OPEN_WEB_UI_API_KEY }}
         API_URL: ${{ vars.API_URL }}
        run: |
          cd genai
          pytest