name: Realtime tests

on:
  pull_request:
    paths:
      - 'realtime/**'
  workflow_dispatch:

jobs:
  server-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Start containers
        run: |
          docker compose run --rm --entrypoint="go test ./..." realtime